const data = [
  { puzzleNumber: 691, words: ["waits", "round", "chore", "grovy", "broom"] },
  { puzzleNumber: 690, words: ["chart", "ethic"] },
  { puzzleNumber: 689, words: ["treat", "ahold", "wacko", "socia", "cocoa",] },
  { puzzleNumber: 688, words: ["plank", "balot", "agloo", "aglow"] },
  { puzzleNumber: 687, words: ["north", "macho", "helos", "ahold", "ghoul"] },
  { puzzleNumber: 686, words: ["testy", "place", "added", "anger"] },
  {
    puzzleNumber: 685,
    words: ["fubar", "broke", "boney", "begot", "bebop", "below"],
  },
  { puzzleNumber: 684, words: ["tenor", "plaid", "puffy", "guppy"] },
  { puzzleNumber: 683, words: ["avert", "prune", "ridge", "dorse", "horde"] },
  { puzzleNumber: 682, words: ["skips", "stank", "smoke", "sulky"] },
  { puzzleNumber: 680, words: ["inter", "dough", "sappy", "plack", "plaza"] },
  { puzzleNumber: 679, words: ["dream", "redan", "cedar"] },
  { puzzleNumber: 678, words: ["crowd", "cater", "cigar", "circa"] },
  { puzzleNumber: 677, words: ["bilge", "guilt", "igloo", "logic"] },
  { puzzleNumber: 676, words: ["tears", "petri", "metro"] },
  {
    puzzleNumber: 675,
    words: ["deign", "erase", "morel", "voter", "power", "joker"],
  },
  { puzzleNumber: 674, words: ["decaf", "drips", "dilly", "dight", "ditto"] },
  { puzzleNumber: 673, words: ["boast", "liked", "fungi", "unity", "unzip"] },
  {
    puzzleNumber: 672,
    words: ["livid", "fresh", "error", "crone", "trope", "broke"],
  },
  { puzzleNumber: 671, words: ["would", "skips", "hacky", "kayak"] },
  { puzzleNumber: 670, words: ["bundt", "trick", "atoll", "lasts", "plate"] },
  { puzzleNumber: 669, words: ["press", "apply", "chimp", "thump"] },
  { puzzleNumber: 668, words: ["grass", "flown", "notch", "honey", "hound"] },
  { puzzleNumber: 667, words: ["stiff", "cliff", "griff", "whiff"] },
  { puzzleNumber: 666, words: ["games", "blend", "dwell", "dwelt"] },
  { puzzleNumber: 665, words: ["brine", "stung", "gland", "agony"] },
  { puzzleNumber: 664, words: ["rerun", "piped", "fries", "thief"] },
  { puzzleNumber: 662, words: ["bones", "board", "boral", "borax"] },
  { puzzleNumber: 661, words: ["style", "qualm"] },
  { puzzleNumber: 657, words: ["swear", "diner", "nuder", "under"] },
  { puzzleNumber: 656, words: ["power", "elect", "leave", "leans", "leafy"] },
  { puzzleNumber: 655, words: ["moors", "small", "smash"] },
  { puzzleNumber: 654, words: ["primp", "rider", "ratio"] },
  { puzzleNumber: 653, words: ["inter", "proud", "rooks", "glory", "flora"] },
  { puzzleNumber: 652, words: ["suede", "sonar", "stool", "stows", "stock"] },
  { puzzleNumber: 651, words: ["train", "polar", "razes", "march"] },
  { puzzleNumber: 648, words: ["preps", "stole", "asset", "inset", "beset"] },
  {
    puzzleNumber: 644,
    words: ["visit", "glade", "frown", "purry", "curry", "hurry"],
  },
  { puzzleNumber: 643, words: ["train", "crust", "grout"] },
  { puzzleNumber: 642, words: ["slang", "staid"] },
  { puzzleNumber: 641, words: ["group", "quilt", "bundt", "duvet"] },
  { puzzleNumber: 640, words: ["revel", "sacks", "downy", "tough"] },
  { puzzleNumber: 639, words: ["paint", "frogs", "glove"] },
  { puzzleNumber: 638, words: ["stole", "owned", "defog", "credo"] },
  { puzzleNumber: 637, words: ["bored", "stuck", "catty", "yacht"] },
  { puzzleNumber: 636, words: ["video", "fresh", "table", "mealy"] },
  { puzzleNumber: 635, words: ["bloop", "crude", "cedar", "cider"] },
  { puzzleNumber: 634, words: ["evens", "yeesh", "sleet", "sweep"] },
  { puzzleNumber: 633, words: ["ghast", "poops", "surly"] },
  { puzzleNumber: 632, words: ["disco", "plane", "flame", "blame"] },
  { puzzleNumber: 631, words: ["woops", "death", "mirth", "girth", "birth"] },
  { puzzleNumber: 629, words: ["would", "later", "riles", "repel", "revel"] },
  { puzzleNumber: 628, words: ["maven", "slice", "probe", "there", "where"] },
  { puzzleNumber: 627, words: ["bough", "angle", "regal"] },
  { puzzleNumber: 626, words: ["bread", "score", "horse"] },
  { puzzleNumber: 625, words: ["right", "pines", "pinny", "pinky"] },
  {
    puzzleNumber: 624,
    words: ["cafes", "block", "occur", "tonic", "topic", "toxic"],
  },
  { puzzleNumber: 623, words: ["plant", "trine", "trend"] },
  {
    puzzleNumber: 622,
    words: ["crook", "blame", "pains", "assay", "squad", "squat"],
  },
  { puzzleNumber: 621, words: ["stoic", "broke", "abode", "above"] },
  { puzzleNumber: 618, words: ["delay", "emote", "biome", "moose"] },
  { puzzleNumber: 617, words: ["going", "rowed", "bouts", "cooky", "polka"] },
  { puzzleNumber: 616, words: ["robot", "corgi", "pored", "worse"] },
  { puzzleNumber: 615, words: ["meter", "ruins", "spurt", "syrup"] },
  { puzzleNumber: 614, words: ["boots", "wrath", "petty", "nifty", "fifty"] },
  { puzzleNumber: 613, words: ["shard", "array", "arbor"] },
  { puzzleNumber: 612, words: ["about", "malus", "vague"] },
  {
    puzzleNumber: 611,
    words: ["tarry", "error", "refer", "rider", "river", "riser", "riper"],
  },
  {
    puzzleNumber: 610,
    words: ["whole", "bunny", "puffy", "sucky", "dummy", "ruddy"],
  },
  {
    puzzleNumber: 609,
    words: ["tacos", "shone", "moose", "gloss", "dross", "kiosk"],
  },
  { puzzleNumber: 608, words: ["fully", "latch", "altar", "avail"] },
  { puzzleNumber: 607, words: ["algae", "brave", "taste", "cache"] },
  { puzzleNumber: 606, words: ["salty", "dared", "manic", "magic"] },
  { puzzleNumber: 605, words: ["fiber", "plant", "lacks", "sally", "salsa"] },
  { puzzleNumber: 604, words: ["brink", "thong", "mound", "pound", "sound"] },
  { puzzleNumber: 603, words: ["tummy", "round", "laugh", "usage"] },
  { puzzleNumber: 602, words: ["baggy", "grail", "giant"] },
  {
    puzzleNumber: 601,
    words: ["tired", "deeps", "death", "delve", "defog", "debug"],
  },
  {
    puzzleNumber: 600,
    words: ["tango", "place", "deads", "ready", "beady", "heady"],
  },
  { puzzleNumber: 599, words: ["scowl", "shear", "sated", "stage"] },
  { puzzleNumber: 598, words: ["elbow", "glitz", "plaid", "flair"] },
  { puzzleNumber: 597, words: ["crate", "abode", "apple"] },
  { puzzleNumber: 596, words: ["wrong", "sneak", "punty", "linty", "ninth"] },
  { puzzleNumber: 595, words: ["cargo", "batch", "fancy", "dance"] },
  {
    puzzleNumber: 594,
    words: ["scour", "whump", "guide", "unity", "until", "unlit"],
  },
  {
    puzzleNumber: 593,
    words: ["under", "chill", "smoky", "gassy", "pasty", "tasty"],
  },
  { puzzleNumber: 592, words: ["sicks", "scalp", "scold"] },
  { puzzleNumber: 591, words: ["gulps", "fares", "stirs", "cross"] },
  { puzzleNumber: 590, words: ["boxer", "drive", "grave", "crave"] },
  { puzzleNumber: 589, words: ["stall", "guise", "winos", "dishy", "fishy"] },
  { puzzleNumber: 588, words: ["worse", "guard", "churn", "flirt"] },
  { puzzleNumber: 587, words: ["rifts", "array", "lorry", "worry"] },
  {
    puzzleNumber: 586,
    words: ["jazzy", "gurdy", "whiny", "peppy", "felty", "beefy"],
  },
  { puzzleNumber: 585, words: ["minor", "mails", "maize"] },
  { puzzleNumber: 584, words: ["proud", "touts", "count"] },
  { puzzleNumber: 583, words: ["sleep", "elate", "elope", "elude"] },
  { puzzleNumber: 582, words: ["bosun", "grimy", "meany", "mazey", "matey"] },
  { puzzleNumber: 581, words: ["float", "glide", "plumb", "blurb"] },
  { puzzleNumber: 580, words: ["repel", "ulcer", "alter"] },
  { puzzleNumber: 578, words: ["brits", "rodeo", "chard"] },
  { puzzleNumber: 577, words: ["build", "apode", "adopt"] },
  { puzzleNumber: 576, words: ["maths", "groin", "drove", "frock"] },
  { puzzleNumber: 575, words: ["flows", "sneer", "spire"] },
  { puzzleNumber: 574, words: ["hinge", "droop", "vocal", "loams", "koala"] },
  { puzzleNumber: 573, words: ["kempt", "lambs", "woman", "adman", "human"] },
  { puzzleNumber: 571, words: ["anime", "eager", "peats", "leapt"] },
  { puzzleNumber: 570, words: ["scant", "sneak", "sedan"] },
  { puzzleNumber: 569, words: ["tired", "piece", "pixie"] },
  { puzzleNumber: 568, words: ["sorry", "adore", "opera"] },
  { puzzleNumber: 567, words: ["sword", "ponce", "ovine", "melon", "lemon"] },
  { puzzleNumber: 566, words: ["scrat", "guild", "libel", "belie"] },
  { puzzleNumber: 565, words: ["awake", "keeps", "sleek"] },
  { puzzleNumber: 564, words: ["offal", "layed", "layer"] },
  { puzzleNumber: 563, words: ["clink", "niche", "panic", "antic"] },
  { puzzleNumber: 562, words: ["train", "first", "shirt", "skirt"] },
  { puzzleNumber: 561, words: ["klutz", "drive", "swine", "whine"] },
  { puzzleNumber: 560, words: ["haste", "valor", "gaily", "wally", "manly"] },
  { puzzleNumber: 559, words: ["knave", "iotas", "polar", "molar"] },
  { puzzleNumber: 556, words: ["tower", "dough", "foods", "mondo", "condo"] },
  {
    puzzleNumber: 555,
    words: ["poops", "frack", "delve", "midge", "nudge", "budge", "judge"],
  },
  {
    puzzleNumber: 554,
    words: ["groom", "chart", "intra", "sutra", "tetra", "extra"],
  },
  { puzzleNumber: 553, words: ["power", "podge", "posse", "poise"] },
  {
    puzzleNumber: 552,
    words: ["gouge", "dorky", "coral", "forma", "sorta", "porta", "iorta"],
  },
  { puzzleNumber: 551, words: ["mason", "fried", "bevel", "wheel", "excel"] },
  { puzzleNumber: 550, words: ["hoist", "crude", "furry", "augur", "lunar"] },
  { puzzleNumber: 549, words: ["winch", "heigh", "shirk", "third"] },
  {
    puzzleNumber: 545,
    words: ["focus", "avoid", "growl", "tromp", "prone", "probe"],
  },
  { puzzleNumber: 544, words: ["hotel", "drill", "rival"] },
  { puzzleNumber: 543, words: ["chomp", "grade", "lunas", "usual"] },
  { puzzleNumber: 542, words: ["nerve", "badge", "slice", "smote", "spoke"] },
  { puzzleNumber: 541, words: ["knell", "scalp", "apply"] },
  { puzzleNumber: 540, words: ["grand", "lanes", "eaten", "naive"] },
  { puzzleNumber: 539, words: ["piano", "donor", "flown", "snobs", "knock"] },
  { puzzleNumber: 538, words: ["learn", "roars", "fraud", "braid"] },
  { puzzleNumber: 537, words: ["focus", "after", "infer"] },
  { puzzleNumber: 536, words: ["train", "emote", "gothy", "doubt", "joust"] },
  { puzzleNumber: 535, words: ["dross", "blurt", "rebar", "caber", "amber"] },
  { puzzleNumber: 534, words: ["blink", "knots", "wonky", "woken"] },
  { puzzleNumber: 533, words: ["snowy", "float", "abode", "adore"] },
  { puzzleNumber: 532, words: ["droop", "torso"] },
  { puzzleNumber: 531, words: ["clogs", "chart", "champ", "chafe"] },
  { puzzleNumber: 530, words: ["phage", "error", "ennui", "elect", "eject"] },
  {
    puzzleNumber: 529,
    words: ["trash", "stoop", "stuck", "stung", "stuff", "studs", "study"],
  },
  { puzzleNumber: 528, words: ["wreck", "feint", "boned", "nudes", "undue"] },
  { puzzleNumber: 527, words: ["break", "depth", "tepid"] },
  { puzzleNumber: 526, words: ["chaos", "alpha", "happy"] },
  { puzzleNumber: 525, words: ["alloy", "blade", "pleat", "clear", "clean"] },
  { puzzleNumber: 524, words: ["faked", "blows", "unity", "pithy", "itchy"] },
  { puzzleNumber: 523, words: ["feast"] },
  { puzzleNumber: 522, words: ["lunge", "chore", "arise", "tribe", "drive"] },
  {
    puzzleNumber: 521,
    words: ["buggy", "fixed", "snipe", "prize", "price", "prime"],
  },
  { puzzleNumber: 520, words: ["couch", "groan", "ovals", "patio", "axiom"] },
  { puzzleNumber: 519, words: ["today", "walks", "crazy", "brave"] },
  {
    puzzleNumber: 518,
    words: ["eerie", "creed", "shear", "opera", "alert", "avert"],
  },
  { puzzleNumber: 517, words: ["skill", "blade", "clout", "glyph"] },
  { puzzleNumber: 516, words: ["wield", "scene", "there"] },
  {
    puzzleNumber: 515,
    words: ["froze", "reels", "tired", "waver", "caper", "maker", "baker"],
  },
  { puzzleNumber: 514, words: ["bogey", "crush", "stark", "snarl"] },
  { puzzleNumber: 513, words: ["month", "murky", "maple"] },
  { puzzleNumber: 512, words: ["brunt", "plank", "deans", "inane"] },
  { puzzleNumber: 511, words: ["chain", "break", "maple", "valet"] },
  { puzzleNumber: 510, words: ["vegan", "pedal", "medal"] },
  { puzzleNumber: 509, words: ["color", "shift", "taiga", "unite"] },
  { puzzleNumber: 508, words: ["jazzy", "lanky", "nappy", "rainy"] },
  { puzzleNumber: 507, words: ["frock", "thine", "gales", "swell", "spell"] },
  { puzzleNumber: 506, words: ["botch", "biker", "beige", "begin"] },
  { puzzleNumber: 505, words: ["dream", "angel", "leash", "scale", "stale"] },
  { puzzleNumber: 504, words: ["again", "drape", "dread", "dream"] },
  { puzzleNumber: 503, words: ["frown", "chomp", "photo"] },
  { puzzleNumber: 502, words: ["knife", "growl", "sloth", "blood", "aloud"] },
  { puzzleNumber: 501, words: ["spoon", "plant", "inept"] },
  {
    puzzleNumber: 500,
    words: ["onion", "night", "pinch", "pined", "pines", "piney"],
  },
  { puzzleNumber: 499, words: ["hyped", "porky", "spicy", "aptly"] },
  { puzzleNumber: 498, words: ["every", "laugh", "waltz"] },
  { puzzleNumber: 497, words: ["fight", "diode", "riven", "piles", "libel"] },
  { puzzleNumber: 496, words: ["crash", "sauna", "sedan", "sneak"] },
  { puzzleNumber: 495, words: ["storm", "quark", "faire", "carry"] },
  {
    puzzleNumber: 494,
    words: ["grief", "folds", "flown", "flock", "float", "flout"],
  },
  { puzzleNumber: 493, words: ["cloth", "roads", "women", "boggy", "foggy"] },
  { puzzleNumber: 492, words: ["porch", "built", "adult", "fault"] },
  { puzzleNumber: 491, words: ["spank", "butte", "guild", "humor", "mummy"] },
  { puzzleNumber: 490, words: ["later", "dowel", "spiel"] },
  { puzzleNumber: 489, words: ["fluff", "adopt", "crone", "grove"] },
  { puzzleNumber: 488, words: ["haunt", "noise", "pined", "denim"] },
  {
    puzzleNumber: 487,
    words: ["allay", "tooth", "verve", "rigid", "primp", "quirk"],
  },
  { puzzleNumber: 486, words: ["foggy", "quell", "strep", "dents", "exist"] },
  { puzzleNumber: 485, words: ["doing", "fines", "skein", "stein"] },
  { puzzleNumber: 484, words: ["ditzy", "words", "spade"] },
  { puzzleNumber: 483, words: ["gorge", "sunny", "cliff", "catch"] },
  { puzzleNumber: 482, words: ["mound", "ovary", "grope", "riots", "floor"] },
  { puzzleNumber: 480, words: ["clued", "aback", "mimic", "ionic"] },
  { puzzleNumber: 479, words: ["clots", "ralph", "dally", "valid"] },
];

export default data;
